# Generated by Django 4.2 on 2023-04-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pedido_produtos_pedido_nome_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Nome_pedido',
            new_name='nome_pedido',
        ),
    ]
