# Generated by Django 4.2 on 2023-05-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_pedido_pedido_nome_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
    ]
