# Generated by Django 4.2 on 2023-05-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_data_nascimento_cliente_data_de_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_de_nascimento',
            new_name='data_de_Nascimento',
        ),
    ]
